/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BillRouteImport } from './routes/bill'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWebhookRouteImport } from './routes/api/webhook'

const BillRoute = BillRouteImport.update({
  id: '/bill',
  path: '/bill',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookRoute = ApiWebhookRouteImport.update({
  id: '/api/webhook',
  path: '/api/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bill': typeof BillRoute
  '/api/webhook': typeof ApiWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bill': typeof BillRoute
  '/api/webhook': typeof ApiWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bill': typeof BillRoute
  '/api/webhook': typeof ApiWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bill' | '/api/webhook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bill' | '/api/webhook'
  id: '__root__' | '/' | '/bill' | '/api/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillRoute: typeof BillRoute
  ApiWebhookRoute: typeof ApiWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bill': {
      id: '/bill'
      path: '/bill'
      fullPath: '/bill'
      preLoaderRoute: typeof BillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook': {
      id: '/api/webhook'
      path: '/api/webhook'
      fullPath: '/api/webhook'
      preLoaderRoute: typeof ApiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillRoute: BillRoute,
  ApiWebhookRoute: ApiWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
